WCS\CoavBundle\Entity\Terrain:
    type: entity
    table: null
    repositoryClass: WCS\CoavBundle\Repository\TerrainRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        icao:
            type: string
            length: '4'
            unique: true
        latitude:
            type: float
        longitude:
            type: float
        city:
            type: string
            length: 255
            nullable: true
        country:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
